app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('/category/{categoty_slug}', 'CategoryController@categoryList');

Route::get('/albom/{albom_slug}', 'AlbomController@albomPhotosList');

Route::get('/albom/{albom_slug}/all', 'AlbomController@all');

Route::get('/image/{image_slug}', 'ImageController@oneImage');

Route::get('search/{query}/{page?}', 'SearchController@show');
Route::get('search', 'SearchController@index');

//Route::get('home', 'HomeController@index');

Route::post('/admin/password', 'AdminController@changePassword');

Route::get('/admin/sitemap', 'AdminController@sitemapGen');

Route::get('admin/settings/all', 'AdminSettingController@all');
Route::resource('admin/settings', 'AdminSettingController');
Route::get('admin/settings/del/{id}', 'AdminSettingController@del');

Route::get('admin/categories/all', 'AdminCategoryController@all');
Route::resource('admin/categories', 'AdminCategoryController');
Route::get('admin/categories/del/{id}', 'AdminCategoryController@del');
Route::post('admin/categories/on_off', 'AdminCategoryController@onOff');
Route::post('admin/categories/del_many', 'AdminCategoryController@delMany');

Route::get('admin/alboms/all', 'AdminAlbomController@all');
Route::post('admin/alboms/change_visible_many', 'AdminAlbomController@changeVisibleMany');
Route::post('admin/alboms/del_cat', 'AdminAlbomController@delCat');
Route::post('admin/alboms/add_cat', 'AdminAlbomController@addCat');
Route::match(array('GET', 'POST'),'admin/alboms/filter', ['as' => 'albomFilter', 'uses' => 'AdminAlbomController@filter']);
Route::resource('admin/alboms', 'AdminAlbomController');
Route::get('admin/alboms/del/{id}', 'AdminAlbomController@del');
Route::post('admin/alboms/del_many', 'AdminAlbomController@delMany');

Route::get('admin/images/all', 'AdminImageController@all');
Route::post('admin/images/change_visible_many', 'AdminImageController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/images/filter', ['as' => 'imageFilter', 'uses' => 'AdminImageController@filter']);
Route::resource('admin/images', 'AdminImageController');
Route::get('admin/images/del/{id}', 'AdminImageController@del');
Route::post('admin/images/del_many', 'AdminImageController@delMany');
Route::post('admin/images/change_image_albom', 'AdminImageController@changeImageAlbom');

Route::get('admin/pages/all', 'AdminPageController@all');
Route::post('admin/pages/change_visible_many', 'AdminPageController@changeVisibleMany');
Route::post('admin/pages/filter', 'AdminPageController@filter');
Route::resource('admin/pages', 'AdminPageController');
Route::get('admin/pages/del/{id}', 'AdminPageController@del');
Route::post('admin/pages/del_many', 'AdminPageController@delMany');
Route::post('admin/pages/change_page_cat', 'AdminPageController@changePageCategory');

Route::resource('admin/vk_parser', 'AdminVkParserController');

Route::resource('admin/meta_auto', 'AdminMetaAutoController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Models/Image.php
<?php namespace App\Models;

 /**
 * This is the Image model. 
 * It allow us to interact with the 'images' table 
 * 
 * @package Models
 * @author Den
 */
use Illuminate\Database\Eloquent\Model;

class Image extends Model {

  /**
   * The database table used by the model.
   *
   * @var string
   */
  protected $table = 'images';

  /**
   * The attributes that are mass not assignable.
   *
   * @var array
   */
  protected $guarded = ['id'];

  /**
   * The attributes excluded from the model's JSON form.
   *
   * @var array
   */
  protected $hidden = [];
 
 /**
   * Defines the belongsTo/hasMany (one to many) relationship between Image and Albom models
   *
   * @return mixed
   */
  public function albom() {
    return $this->belongsTo('App\Models\Albom');
  }  
 
}

app/Http/Controllers/ImageController.php
<?php namespace App\Http\Controllers;

use App\Repositories\ImageRepository;

/**
 * ImageController (Frontend. Show one image)
 * 
 * 
 * @package  Controllers
 * @author    Den
 */

class ImageController extends Controller {

    /**
     * Image Repository
     *
     * @var App\Repositories\ImageRepository
     */
    protected $image;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(ImageRepository $image) {
        $this->middleware('guest');
        $this->image = $image;
    }

    /**
     * Show the one Image.
     *
     * @return Response
     */
    public function oneImage($imageSlug) {
        $data = $this->image->oneImage($imageSlug);
        return view('image', $data);
    }

}

resources/views/admin/images/create.blade.php
@extends('part_app')

@section('content')

<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        <div class="panel panel-default">
            <div class="panel-heading">Create New Image </div>

            <div class="panel-body">

                {!! Form::model(new App\Models\Image, ['route' => ['admin.images.store'],'role'=>'form','class'=>'block small center login','style'=>'height:80%']) !!}
                @include('admin/images/_partials/form', ['submit_text' => 'New Image', 'alboms' => $alboms])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/images/del.blade.php
@extends('part_app')

@section('content')
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete image with id "{{$id}}"</h4>
      </div>
      <div class="modal-body">
        <p>Are you shure?</p>
      </div>
      <div class="modal-footer">
          {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.images.destroy', $id))) !!}
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
         <input class="form-control" name="page" type="hidden" value="<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" id="page">
         <input class="form-control" name="albSel" type="hidden" value="<?php if (isset($_GET['albSel'])) echo $_GET['albSel']; ?>" id="albSel">
         {!! Form::submit('Yes', array('class' => 'btn btn-primary')) !!}
                     
             {!! Form::close() !!}
      </div>
@stop

resources/views/admin/images/edit.blade.php
@extends('part_app')

@section('content')
<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        
        <div class="panel panel-default">
            
            <div class="panel-heading">Edit Image "{{ $image->title }}" with ID "{{ $image->id }}" </div>

            <div class="panel-body">

                {!! Form::model($image, ['method' => 'PATCH', 'route' => ['admin.images.update', $image->id],'role'=>'form','class'=>'block small center login','style'=>'height:80%', 'files'=>true]) !!}
                @include('admin/images/_partials/form', ['submit_text' => 'Edit Image', 'alboms' => $alboms])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/images/index.blade.php
<div class="container">

    @if (Session::has('message'))
            <div class="flash alert-info">
                <p>{!! Session::get('message') !!}</p>
            </div>
    @endif

   @if (Session::has('error'))
            <div class="flash alert-danger">
                <p>{!! Session::get('error') !!}</p>
            </div>
   @endif
            @if ($errors->any())
            <div class='flash alert-danger'>
                @foreach ( $errors->all() as $error )
                <p>{{ $error }}</p>
                @endforeach
            </div>
            @endif

	<div class="col-md-11 col-md-offset">
   <div class="panel panel-default">
				<div class="panel-heading">Administration Panel - Фотографии</div>

				<div class="panel-body">
            <a class="delete_selected btn btn-danger disabled">Delete Selected</a>

            <div class="col-md-13 col-md-offset" style="float:right;">
            {!! Form::open(array('class' => 'form-inline', 'method' => 'POST', 'url' => '/admin/images/filter')) !!}

             <input class="form-control" name="limit" type="text" value="{{isset($limit) ? $limit : '10'}}" placeholder="макс. кол-во (шт.)">
             <select class="form-control albomus" name="albSel" style="width:200px">
                                         <option value="">Любой альбом</option>
                                         @foreach ($alboms as $albom)
                                         <option  value="{{$albom->id}}"  @if(isset($albomSel)&&($albom->id == $albomSel)) selected @endif>
                                                  {{$albom->title}}
                                         </option>
                                         @endforeach
             </select>
             <input type="checkbox" name="sort" @if(isset($sort)&&($sort == 'desc')) checked @endif />desc(set)/asc
             {!! Form::submit('apply', array('class' => 'btn btn-info')) !!}
             {!! Form::close() !!}
             </div>
            {!! link_to_route('admin.images.create', 'Create New Image', array() ,array('class' => '', 'data-toggle'=>'modal', 'data-target'=>'#createImage') ) !!}<br><br>
             <div class="table-responsive">
                 <table class="table table-bordered" data-search="true" data-url="">
                     <thead>
                         <tr>
                             <th>
                              <div>
                                  <input type="checkbox" id="SelectAll">
                                  Select All
                              </div>
                             </th>
                             <th data-sortable="true">ID</th>
                             <th>Albom</th>
                             <th>Title</th>
                             <th>Alt</th>
                             <th>Capt.</th>
                             <th>Descr.</th>
                           
                             <th>Cont.</th>
                           
                             <th>Thumb</th>
                             <th>
                              <div>
                                  <input type="checkbox" id="SelectAllVisible" data-url="images"> Visible
                              </div>
                             </th>
                             <th>Operations</th>
                         </tr>
                     </thead>
                     <tbody>
                        @foreach ($images as $image)
                         <tr>
                             <td>
                                 <div>
                                     <input type="checkbox" class="images-delete" id="id{{$image->id}}" data-id="{{$image->id}}">
                                 </div>
                             </td>
                             <td class="delete_toggler">{{$image->id}}</td>
                             <td>
                                 <div class="form-group block" data-id="{{$image->id}}">

                                     <select class="form-control albs" id="alb{{$image->id}}" data-id="{{$image->id}}" style="">
                                         @foreach ($alboms as $albom)
                                         <option albom-id="{{$albom->id}}" value="{{$image->id}}" @if ($image->albom_id == $albom->id) selected @endif>
                                                  {{$albom->title}}
                                         </option>
                                         @endforeach
                                     </select>

                                 </div>
                             </td>
                             <td>
                                 <div data-toggle="tooltip" data-placement="bottom" title="{{$image->title}}">
                                     {!!mb_strimwidth($image->title, 0, 10, "...")!!}
                                 </div>
                             </td>
                             <td>
                                 <div data-toggle="tooltip" data-placement="bottom" title="{{$image->alt_text}}">
                                     {!!mb_strimwidth($image->alt_text, 0, 10, "...")!!}
                                 </div>
                             </td>
                             <td>
                                 <div data-toggle="tooltip" data-placement="bottom" title="{{$image->caption}}">
                                     {!!mb_strimwidth($image->caption, 0, 10, "...")!!}
                                 </div>
                             </td>
                             <td>
                                 <div data-toggle="tooltip" data-placement="bottom" title="{{$image->description}}">
                                     {!!mb_strimwidth($image->description, 0, 10, "...")!!}
                                 </div>
                             </td>
                         
                             <td>
                                 <div data-toggle="tooltip" data-placement="bottom" title="{{$image->content}}">
                                     {!!mb_strimwidth($image->content, 0, 10, "...")!!}
                                 </div>
                             </td>
                             <!--<td>{{$image->rem}}</td>-->
                              <td style="height:130px;width:130px"><img src="{{$image->url_thumb}}" style="height:130px;width:130px"></td>
                             <td>
                              <input type="checkbox" class="visible-change" data-url="images" name="visible" @if($image->visible==1) checked @endif data-id="{{$image->id}}">
                             </td>
                             <td>
                                 <a href="/admin/images/{{$image->id}}/edit?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" class="btn btn-info" data-toggle="modal" data-target="#editImage{{$image->id}}">Edit</a>
                                 <div id="editImage{{$image->id}}" class="modal fade" >
                                     <div class="modal-dialog">
                                         <div class="modal-content" style="width:860px">

                                         </div>
                                     </div>
                                 </div>

                                 <a href="/admin/images/del/{{$image->id}}?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>&albSel={{$image->albom_id}}" class="btn btn-danger" data-toggle="modal" data-target="#delImage{{$image->id}}">Delete</a>

                                 <div id="delImage{{$image->id}}"  class="modal fade">
                                     <div class="modal-dialog">
                                         <div class="modal-content">

                                         </div>
                                     </div>
                                 </div>

                             </td>
                         </tr>
                         @endforeach
                     </tbody>
                 </table>

                 @if ($images && (!isset($all)))

                    @if (!isset($limit))
                    {!! $images->appends(Input::except('page'))->render() !!}
                    <ul class="pagination">
                    <li><a href="/admin/images/all">All</a></li>
                    </ul>
                    @else
                    <ul class="pagination">
                    <li><a href="/admin/images">1</a></li>
                    </ul>
                    @endif

                 @else
                 <ul class="pagination">
                 <li><a href="/admin/images">1</a></li>
                 </ul>
                 @endif
                 <input type="hidden" id="pageNumb" value="<?php if (isset($_GET['page'])) echo $_GET['page']; else echo '1'; ?>">
             </div>
        </div>

    </div>
</div>

</div>

@include('admin._partials.del-modal', ['url' => '/admin/images/del_many'])

@include('admin._partials.modal', ['elementId' => 'createImage', 'alboms' => $alboms])

@include('admin.js')