app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('/category/{categoty_slug}', 'CategoryController@categoryList');

Route::get('/albom/{albom_slug}', 'AlbomController@albomPhotosList');

Route::get('/albom/{albom_slug}/all', 'AlbomController@all');

Route::get('/image/{image_slug}', 'ImageController@oneImage');

Route::get('search/{query}/{page?}', 'SearchController@show');
Route::get('search', 'SearchController@index');

//Route::get('home', 'HomeController@index');

Route::post('/admin/password', 'AdminController@changePassword');

Route::get('/admin/sitemap', 'AdminController@sitemapGen');

Route::get('admin/settings/all', 'AdminSettingController@all');
Route::resource('admin/settings', 'AdminSettingController');
Route::get('admin/settings/del/{id}', 'AdminSettingController@del');

Route::get('admin/categories/all', 'AdminCategoryController@all');
Route::resource('admin/categories', 'AdminCategoryController');
Route::get('admin/categories/del/{id}', 'AdminCategoryController@del');
Route::post('admin/categories/on_off', 'AdminCategoryController@onOff');
Route::post('admin/categories/del_many', 'AdminCategoryController@delMany');

Route::get('admin/alboms/all', 'AdminAlbomController@all');
Route::post('admin/alboms/change_visible_many', 'AdminAlbomController@changeVisibleMany');
Route::post('admin/alboms/del_cat', 'AdminAlbomController@delCat');
Route::post('admin/alboms/add_cat', 'AdminAlbomController@addCat');
Route::match(array('GET', 'POST'),'admin/alboms/filter', ['as' => 'albomFilter', 'uses' => 'AdminAlbomController@filter']);
Route::resource('admin/alboms', 'AdminAlbomController');
Route::get('admin/alboms/del/{id}', 'AdminAlbomController@del');
Route::post('admin/alboms/del_many', 'AdminAlbomController@delMany');

Route::get('admin/images/all', 'AdminImageController@all');
Route::post('admin/images/change_visible_many', 'AdminImageController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/images/filter', ['as' => 'imageFilter', 'uses' => 'AdminImageController@filter']);
Route::resource('admin/images', 'AdminImageController');
Route::get('admin/images/del/{id}', 'AdminImageController@del');
Route::post('admin/images/del_many', 'AdminImageController@delMany');
Route::post('admin/images/change_image_albom', 'AdminImageController@changeImageAlbom');

Route::get('admin/pages/all', 'AdminPageController@all');
Route::post('admin/pages/change_visible_many', 'AdminPageController@changeVisibleMany');
Route::post('admin/pages/filter', 'AdminPageController@filter');
Route::resource('admin/pages', 'AdminPageController');
Route::get('admin/pages/del/{id}', 'AdminPageController@del');
Route::post('admin/pages/del_many', 'AdminPageController@delMany');
Route::post('admin/pages/change_page_cat', 'AdminPageController@changePageCategory');

Route::resource('admin/vk_parser', 'AdminVkParserController');

Route::resource('admin/meta_auto', 'AdminMetaAutoController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Models/Albom.php
<?php namespace App\Models;

 /**
 * This is the Albom model. 
 * It allow us to interact with the 'alboms' table 
 * 
 * @package Models
 * @author Den
 */
use Illuminate\Database\Eloquent\Model;

class Albom extends Model {

  /**
   * The database table used by the model.
   *
   * @var string
   */
  protected $table = 'alboms';

  /**
   * The attributes that are mass not assignable.
   *
   * @var array
   */
  protected $guarded = ['id'];

  /**
   * The attributes excluded from the model's JSON form.
   *
   * @var array
   */
  protected $hidden = [];
 
  /**
   * Defines the belongsToMany/belongsToMany (many to many) relationship between Albom and Category models
   *
   * @return mixed
   */
  public function categories() {
    return $this->belongsToMany('App\Models\Category', 'alboms_categories', 'albom_id', 'category_id');
  } 
  
  /**
   * Defines the hasMany/belongsTo (one to many) relationship between Albom and Image models
   *
   * @return mixed
   */
  public function images() {
    return $this->hasMany('App\Models\Image');
  }
 
}

app/Http/Controllers/AlbomController.php
<?php namespace App\Http\Controllers;

use App\Repositories\AlbomRepository;

/**
 * Albom Controller (Frontend alboms list)
 * 
 * 
 * @package  Controllers
 * @author    Den
 */
class AlbomController extends Controller {

    /**
     * Albom Repository
     *
     * @var App\Repositories\AlbomRepository
     */
    protected $albom;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(AlbomRepository $albom) {
        $this->middleware('guest');
        $this->albom = $albom;
    }

    /**
     * Show the list of Photos in Albom.
     *
     * @return Response
     */
    public function albomPhotosList($albomSlug) {
        $data = $this->albom->albomPhotosList($albomSlug);
        return view('albom', $data);
    }

    public function all($albomSlug) {
        $data = $this->albom->albomPhotosList($albomSlug, $all = 1);
        $data['limit'] = 1;
        return view('albom', $data);
    }

}

resources/views/admin/alboms/create.blade.php
@extends('part_app')

@section('content')

<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        <div class="panel panel-default">
            <div class="panel-heading">Create New Albom</div>

            <div class="panel-body">

                {!! Form::model(new App\Models\Albom, ['route' => ['admin.alboms.store'],'role'=>'form','class'=>'block small center login','style'=>'height:80%','files'=>true]) !!}
                @include('admin/alboms/_partials/form', ['submit_text' => 'New Albom'])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/alboms/del.blade.php
@extends('part_app')

@section('content')
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete albom with id "{{$id}}"</h4>
      </div>
      <div class="modal-body">
        <p>Are you shure?</p>
      </div>
      <div class="modal-footer">
          {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.alboms.destroy', $id))) !!}
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
         <input class="form-control" name="page" type="hidden" value="<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" id="page">
                {!! Form::submit('Yes', array('class' => 'btn btn-primary')) !!}
                     
             {!! Form::close() !!}
      </div>
@stop

resources/views/admin/alboms/edit.blade.php
@extends('part_app')

@section('content')
<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        
        <div class="panel panel-default">
            
            <div class="panel-heading">Edit Albom "{{ $albom->name }}"</div>

            <div class="panel-body">

                {!! Form::model($albom, ['method' => 'PATCH', 'route' => ['admin.alboms.update', $albom->id],'role'=>'form','class'=>'block small center login','style'=>'height:80%', 'files'=>true]) !!}
                @include('admin/alboms/_partials/form', ['submit_text' => 'Edit Albom'])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/alboms/index.blade.php
<div class="container">

    @if (Session::has('message'))
    <div class="flash alert-info">
        <p>{!! Session::get('message') !!}</p>
    </div>
    @endif
    @if (Session::has('error'))
    <div class="flash alert-danger">
        <p>{!! Session::get('error') !!}</p>
    </div>
    @endif
    @if ($errors->any())
    <div class='flash alert-danger'>
        @foreach ( $errors->all() as $error )
        <p>{{ $error }}</p>
        @endforeach
    </div>
    @endif

    <div class="col-md-11 col-md-offset">
        <div class="panel panel-default">
            <div class="panel-heading">Administration Panel - Альбомы</div>

            <div class="panel-body">
                <a class="delete_selected btn btn-danger disabled">Delete Selected</a>

                <div class="col-md-13 col-md-offset" style="float:right;">
                    {!! Form::open(array('class' => 'form-inline', 'method' => 'POST', 'url' => '/admin/alboms/filter')) !!}

                    <input class="form-control" name="limit" type="text" value="{{isset($limit) ? $limit : '10'}}" placeholder="макс. кол-во (шт.)">
                    <select class="form-control cats" name="catSel" style="">
                        <option value="">Любая категория</option>
                        @foreach ($categories as $category)
                        <option  value="{{$category->id}}"  @if(isset($catSel)&&($category->id == $catSel)) selected @endif>
                                 {{$category->title}}
                    </option>
                    @endforeach
                </select>
                {!! Form::submit('apply', array('class' => 'btn btn-info')) !!}
                {!! Form::close() !!}
            </div>
            {!! link_to_route('admin.alboms.create', 'Create New Albom', array() ,array('class' => '', 'data-toggle'=>'modal', 'data-target'=>'#createAlbom') ) !!}<br><br>
            <div class="table-responsive">
                <table class="table table-bordered" data-search="true" data-url="">
                    <thead>
                        <tr>
                            <th>
                    <div>
                        <input type="checkbox" id="SelectAll">
                        Select All
                    </div>
                    </th>
                    <th data-sortable="true">ID</th>
                    <th>Caregory</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Content</th>
                    <th>Keywords</th>
                    <th>Rem</th>
                    <th>Photo Small</th>
                    <th>
                    <div>
                        <input type="checkbox" id="SelectAllVisible" data-url="alboms"> Visible
                    </div>
                    </th>
                    <th>Operations</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($alboms as $albom)
                        <tr>
                            <td>
                                <div>
                                    <input type="checkbox" class="alboms-delete" id="id{{$albom->id}}" data-id="{{$albom->id}}">
                                </div>
                            </td>
                            <td class="delete_toggler">{{$albom->id}}</td>
                            <td>
                                <div class="form-group block" data-id="{{$albom->id}}">
                                    <div>
                                        <select class="form-control cats" id="catAlb{{$albom->id}}" data-id="{{$albom->id}}" style="width:90%">
                                            <option value="0" selected>Без категории</option>
                                            @foreach ($categories as $category)
                                            <option albom-id="{{$albom->id}}" value="{{$category->id}}">
                                                {{$category->title}}
                                            </option>
                                            @endforeach
                                        </select>
                                        <a href="#" class="addCat" data-id="0" style="float:right; margin-top: -30px" albom-id="{{$albom->id}}">
                                            <i class="fa fa-fw fa-plus-square"></i>
                                        </a>
                                    </div>
                                    @foreach ($albom->categories->all() as $cats)

                                    <div class="catsSel" alb-id="{{$albom->id}}" cat-id="{{$cats->id}}">
                                        {{$cats->title}}
                                        <a href="#" class="delCat" data-id="{{$cats->id}}" albom-id="{{$albom->id}}">
                                            <i class="fa fa-fw fa-minus-square"></i>
                                        </a>

                                    </div>

                                    @endforeach
                                </div>
                            </td>
                            <td>
                                <div data-toggle="tooltip" data-placement="bottom" title="{{$albom->title}}">
                                    {!!mb_strimwidth($albom->title, 0, 10, "...")!!}
                                </div>
                            </td>
                            <td>
                                <div data-toggle="tooltip" data-placement="bottom" title="{{$albom->description}}">
                                    {!!mb_strimwidth($albom->description, 0, 10, "...")!!}
                                </div>
                            </td>

                            <td>
                                <div data-toggle="tooltip" data-placement="bottom" title="{{$albom->content}}">
                                    {!!mb_strimwidth($albom->content, 0, 10, "...")!!}
                                </div>
                            </td>
                            <td>
                                <div data-toggle="tooltip" data-placement="bottom" title="{{$albom->keywords}}">
                                    {!!mb_strimwidth($albom->keywords, 0, 10, "...")!!}
                                </div>
                            </td>
                            <td>{{$albom->rem}}</td>
                            <td><img src="{{$albom->thumb}}" width="130" height="130"></td>
                            <td>
                                <input type="checkbox" class="visible-change" data-url="alboms" name="visible" @if($albom->visible==1) checked @endif data-id="{{$albom->id}}">
                            </td>
                            <td>
                                <a href="/admin/alboms/{{$albom->id}}/edit?page=<?php if (isset($_GET['page'])) echo $_GET['page'];
else echo '1'; ?>&limit={{isset($limit) ? $limit : '10'}}&catSel={{isset($catSel) ? $catSel : ''}}" class="btn btn-info" data-toggle="modal" data-target="#editAlbom{{$albom->id}}">Edit</a>
                                <div id="editAlbom{{$albom->id}}" class="modal fade" >
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                        </div>
                                    </div>
                                </div>

                                <a href="/admin/alboms/del/{{$albom->id}}?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" class="btn btn-danger" data-toggle="modal" data-target="#delAlbom{{$albom->id}}">Delete</a>

                                <div id="delAlbom{{$albom->id}}"  class="modal fade">
                                    <div class="modal-dialog">
                                        <div class="modal-content">

                                        </div>
                                    </div>
                                </div>

                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

                @if ($alboms && (!isset($all)))

                @if (!isset($limit))
                {!! $alboms->appends(Input::except('page'))->render() !!}
                <ul class="pagination">
                    <li><a href="/admin/alboms/all">All</a></li>
                </ul>
                @else
                <ul class="pagination">
                    <li><a href="/admin/alboms">1</a></li>
                </ul>
                @endif

                @else
                <ul class="pagination">
                    <li><a href="/admin/alboms">1</a></li>
                </ul>
                @endif
                <input type="hidden" id="pageNumb" value="<?php if (isset($_GET['page'])) echo $_GET['page'];
else echo '1'; ?>">
            </div>
        </div>

    </div>
</div>

</div>

@include('admin._partials.del-modal', ['url' => '/admin/alboms/del_many'])

@include('admin._partials.modal', ['elementId' => 'createAlbom'])

@include('admin.js')