app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('/category/{categoty_slug}', 'CategoryController@categoryList');

Route::get('/albom/{albom_slug}', 'AlbomController@albomPhotosList');

Route::get('/albom/{albom_slug}/all', 'AlbomController@all');

Route::get('/image/{image_slug}', 'ImageController@oneImage');

Route::get('search/{query}/{page?}', 'SearchController@show');
Route::get('search', 'SearchController@index');

//Route::get('home', 'HomeController@index');

Route::post('/admin/password', 'AdminController@changePassword');

Route::get('/admin/sitemap', 'AdminController@sitemapGen');

Route::get('admin/settings/all', 'AdminSettingController@all');
Route::resource('admin/settings', 'AdminSettingController');
Route::get('admin/settings/del/{id}', 'AdminSettingController@del');

Route::get('admin/categories/all', 'AdminCategoryController@all');
Route::resource('admin/categories', 'AdminCategoryController');
Route::get('admin/categories/del/{id}', 'AdminCategoryController@del');
Route::post('admin/categories/on_off', 'AdminCategoryController@onOff');
Route::post('admin/categories/del_many', 'AdminCategoryController@delMany');

Route::get('admin/alboms/all', 'AdminAlbomController@all');
Route::post('admin/alboms/change_visible_many', 'AdminAlbomController@changeVisibleMany');
Route::post('admin/alboms/del_cat', 'AdminAlbomController@delCat');
Route::post('admin/alboms/add_cat', 'AdminAlbomController@addCat');
Route::match(array('GET', 'POST'),'admin/alboms/filter', ['as' => 'albomFilter', 'uses' => 'AdminAlbomController@filter']);
Route::resource('admin/alboms', 'AdminAlbomController');
Route::get('admin/alboms/del/{id}', 'AdminAlbomController@del');
Route::post('admin/alboms/del_many', 'AdminAlbomController@delMany');

Route::get('admin/images/all', 'AdminImageController@all');
Route::post('admin/images/change_visible_many', 'AdminImageController@changeVisibleMany');
Route::match(array('GET', 'POST'),'admin/images/filter', ['as' => 'imageFilter', 'uses' => 'AdminImageController@filter']);
Route::resource('admin/images', 'AdminImageController');
Route::get('admin/images/del/{id}', 'AdminImageController@del');
Route::post('admin/images/del_many', 'AdminImageController@delMany');
Route::post('admin/images/change_image_albom', 'AdminImageController@changeImageAlbom');

Route::get('admin/pages/all', 'AdminPageController@all');
Route::post('admin/pages/change_visible_many', 'AdminPageController@changeVisibleMany');
Route::post('admin/pages/filter', 'AdminPageController@filter');
Route::resource('admin/pages', 'AdminPageController');
Route::get('admin/pages/del/{id}', 'AdminPageController@del');
Route::post('admin/pages/del_many', 'AdminPageController@delMany');
Route::post('admin/pages/change_page_cat', 'AdminPageController@changePageCategory');

Route::resource('admin/vk_parser', 'AdminVkParserController');

Route::resource('admin/meta_auto', 'AdminMetaAutoController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Models/Category.php
<?php namespace App\Models;

 /**
 * This is the Category model. 
 * It allow us to interact with the 'categories' table 
 * 
 * @package Models
 * @author Den
 */
use Illuminate\Database\Eloquent\Model;

class Category extends Model {

  /**
   * The database table used by the model.
   *
   * @var string
   */
  protected $table = 'categories';

  /**
   * The attributes that are mass not assignable.
   *
   * @var array
   */
  protected $guarded = ['id'];

  /**
   * The attributes excluded from the model's JSON form.
   *
   * @var array
   */
  protected $hidden = [];
 
  /**
   * Defines the belongsToMany/belongsToMany (many to many) relationship between Category and Albom models
   *
   * @return mixed
   */
  public function alboms() {
    return $this->belongsToMany('App\Models\Albom', 'alboms_categories',  'category_id', 'albom_id');
  } 
  
  /**
   * Defines the belongsTo/hasOne (one to one) relationship between Page and Category models
   *
   * @return mixed
   */
  public function page() {
    return $this->hasOne('App\Models\Page');
  }
 
}

app/Http/Controllers/CategoryController.php
<?php namespace App\Http\Controllers;

use App\Repositories\CategoryRepository;
use Input;
use App;

/**
 * Category Controller (Frontend categories list)
 * 
 * 
 * @package  Controllers
 * @author    Den
 */
class CategoryController extends Controller {

    /**
     * Category Repository
     *
     * @var App\Repositories\CategoryRepository
     */
    protected $category;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(CategoryRepository $category) {
        $this->middleware('guest');
        $this->category = $category;
    }

    /**
     * Show the list of Categories.
     *
     * @return Response
     */
    public function categoryList($categorySlug) {

        $page = Input::get('page') ? Input::get('page') : 1;
        $data = $this->category->categoryList($categorySlug, $page);

        if (count($data) >= 1) {
            return view('welcome', $data);
        } else {
            App::abort(404);
        }
    }

}

resources/views/admin/categories/create.blade.php
@extends('part_app')

@section('content')

<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        <div class="panel panel-default">
            <div class="panel-heading">Create New Category </div>

            <div class="panel-body">

                {!! Form::model(new App\Models\Category, ['route' => ['admin.categories.store'],'role'=>'form','class'=>'block small center login','style'=>'height:80%']) !!}
                @include('admin/categories/_partials/form', ['submit_text' => 'New Category'])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/categories/del.blade.php
@extends('part_app')

@section('content')
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete category with id "{{$id}}"</h4>
      </div>
      <div class="modal-body">
        <p>Are you shure?</p>
      </div>
      <div class="modal-footer">
          {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('admin.categories.destroy', $id))) !!}
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
         <input class="form-control" name="page" type="hidden" value="<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" id="page">
                {!! Form::submit('Yes', array('class' => 'btn btn-primary')) !!}
                     
             {!! Form::close() !!}
      </div>
@stop

resources/views/admin/categories/edit.blade.php
@extends('part_app')

@section('content')
<div class="container" style='width:auto;  margin-top: 20px;'>

    <div class="col-md-13 col-md-offset">
        
        <div class="panel panel-default">
            
            <div class="panel-heading">Edit Category "{{ $category->name }}"</div>

            <div class="panel-body">

                {!! Form::model($category, ['method' => 'PATCH', 'route' => ['admin.categories.update', $category->id],'role'=>'form','class'=>'block small center login','style'=>'height:80%']) !!}
                @include('admin/categories/_partials/form', ['submit_text' => 'Edit Category'])
                {!! Form::close() !!}  

            </div>

        </div>

    </div>

</div>
@stop

resources/views/admin/categories/index.blade.php
<div class="container">
    
    @if (Session::has('message'))
            <div class="flash alert-info">
                <p>{!! Session::get('message') !!}</p>
            </div>
    @endif
    @if (Session::has('error'))
            <div class="flash alert-danger">
                <p>{!! Session::get('error') !!}</p>
            </div>
    @endif
            @if ($errors->any())
            <div class='flash alert-danger'>
                @foreach ( $errors->all() as $error )
                <p>{{ $error }}</p>
                @endforeach
            </div>
            @endif
  
	<div class="col-md-11 col-md-offset">
   <div class="panel panel-default">
				<div class="panel-heading">Administration Panel - Категории</div>

				<div class="panel-body">
            <a class="delete_selected btn btn-danger disabled">Delete Selected</a>
            {!! link_to_route('admin.categories.create', 'Create New Category', array() ,array('class' => '', 'data-toggle'=>'modal', 'data-target'=>'#createCategory') ) !!}<br><br>
             <div class="table-responsive"> 
                 <table class="table table-bordered" data-search="true" data-url="">
                     <thead>
                         <tr>
                             <th>
                              <div>
                                  <input type="checkbox" id="SelectAll">
                                  Select All
                              </div>
                             </th>
                             <th data-sortable="true">ID</th>
                             <th>Title</th>
                            
                             <th>On/Off</th>
                             <th>Operations</th>
                         </tr>
                     </thead>
                     <tbody>
                         @foreach ($categories as $category)
                         <tr>
                             <td>
                                 <div>
                                     <input type="checkbox" id="id{{$category->id}}" data-id="{{$category->id}}">
                                 </div>
                             </td>
                             <td class="delete_toggler">{{$category->id}}</td>
                             <td>{{$category->title}}</td>
                         
                             <td>
                              <input type="checkbox" class="categories-visible" name="visible" @if($category->visible==1) checked @endif data-id="{{$category->id}}">
                             </td>
                             <td>
                                 <a href="/admin/categories/{{$category->id}}/edit?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" class="btn btn-info" data-toggle="modal" data-target="#editCategory{{$category->id}}">Edit</a>
                                 <div id="editCategory{{$category->id}}" class="modal fade" >
                                     <div class="modal-dialog">
                                         <div class="modal-content">

                                         </div>
                                     </div>
                                 </div>

                                 <a href="/admin/categories/del/{{$category->id}}?page=<?php if (isset($_GET['page'])) echo $_GET['page']; ?>" class="btn btn-danger" data-toggle="modal" data-target="#delCategory{{$category->id}}">Delete</a>

                                 <div id="delCategory{{$category->id}}"  class="modal fade">
                                     <div class="modal-dialog">
                                         <div class="modal-content">

                                         </div>
                                     </div>
                                 </div>

                             </td>
                         </tr>
                         @endforeach
                     </tbody>
                 </table>

                 @if ($categories && (!isset($all)))

                 {!! $categories->appends(Input::except('page'))->render() !!}
                 <ul class="pagination">
                 <li><a href="/admin/categories/all">All</a></li>
                 </ul>
                 @else
                 <ul class="pagination">
                 <li><a href="/admin/categories">1</a></li>
                 </ul>
                 @endif
                 
             </div>
        </div>
        
    </div> 
</div>
    
</div> 

@include('admin._partials.del-modal', ['url' => '/admin/categories/del_many']) 

@include('admin._partials.modal', ['elementId' => 'createCategory']) 

@include('admin.js')